name: AMail

on:
  workflow_dispatch:
    inputs:
      THE_REPO:
        description: Repository name
        type: string
        required: true

jobs:
  build-binaries:
    strategy:
      matrix:
        os: [ubuntu-20.04,windows-2019 ]
    runs-on: martix.os
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ inputs.THE_REPO }}
          ref: main
          token: ${{ secrets.GH_TOKEN }}
          path: source-code
          sparse-checkout: .

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.6"
