name: Test

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
    steps:
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"
      - name: Test values
        run: |
          echo "test from step 1 (step) = ${{ steps.step1.outputs.test }}"
          echo "test from step 2 (step) = ${{ steps.step2.outputs.test }}"
          echo "test from step 1 (job out) = ${{ jobs.job1.outputs.output1 }}"
          echo "test from step 2 (job out) = ${{ jobs.job1.outputs.output2 }}"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - env:
          OUTPUT1: ${{needs.job1.outputs.output1}}
          OUTPUT2: ${{needs.job1.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
